language: rust
cache: cargo
rust:
- nightly
- beta
- stable
- 1.17.0
env:
  global:
    - RUST_MIN_STACK=16777216
branches:
  only:
    - staging
    - trying
    - master
script:
- |
  cargo build --verbose &&
  cargo test --verbose &&
  cargo build --verbose --no-default-features &&
  cargo test --verbose --no-default-features
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench --verbose --no-run;
  fi
