[package]
name = "shred"
version = "0.4.4"
authors = ["torkleyy <torkleyy@gmail.com>"]
description = """
Dispatches systems in parallel which need read access to some resources,
and write access to others.
"""
readme = "README.md"
documentation = "https://docs.rs/shred"
repository = "https://github.com/slide-rs/shred"
keywords = ["parallel", "systems", "resources", "ecs"]
categories = ["concurrency"]
license = "MIT/Apache-2.0"
exclude = ["bors.toml", ".travis.yml"]

[badges]
travis-ci = { repository = "torkleyy/shred" }

[dependencies]
arrayvec = "0.3"
fnv = "1"
mopa = "0.2"
pulse = "0.5"
rayon = "0.8"
shred-derive = { path = "shred-derive", version = "0.3" }
smallvec = "0.4"

[dev-dependencies]
cgmath = "0.15"
