[package]
name = "shred"
version = "0.5.0"
authors = ["torkleyy <torkleyy@gmail.com>"]
description = """
Dispatches systems in parallel which need read access to some resources,
and write access to others.
"""
readme = "README.md"
documentation = "https://docs.rs/shred"
repository = "https://github.com/slide-rs/shred"
keywords = ["parallel", "systems", "resources", "ecs"]
categories = ["concurrency"]
license = "MIT/Apache-2.0"
exclude = ["bors.toml", ".travis.yml"]

[badges]
travis-ci = { repository = "torkleyy/shred" }

[dependencies]
arrayvec = "0.3"
fxhash = "0.2"
mopa = "0.2"
pulse = { version = "0.5", optional = true }
rayon = { version = "0.8", optional = true }
shred-derive = { path = "shred-derive", version = "0.3" }
smallvec = "0.4"

[dev-dependencies]
cgmath = "0.15"

[features]
default = ["parallel"]
parallel = ["pulse", "rayon"]

[[example]]
name = "par_seq"
required-features = ["parallel"]